name: Aosp Build CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set build date
      id: get-date
      run: | 
        echo ::set-output name=date::$(/bin/date -u "+%Y%m%d")
    - name: execute
      run: chmod +x bac.sh
    - name: build
      run: ./bac.sh
    - name: Kernel Image
      run: cp out/arch/arm64/boot/Image.gz-dtb /home/runner/anykernel3/Image.gz-dtb
    - name: zip it
      run:  cd /home/runner/anykernel3 && zip -r9 linaosp-${{ steps.get-date.outputs.date }}.zip  * -x README linaosp-${{ steps.get-date.outputs.date }}.zip
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel
        path: /home/runner/anykernel3/linaosp-${{ steps.get-date.outputs.date }}.zip
