name: Proton Build CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: cl
      run: git clone https://github.com/walternewtz/android_kernel_xiaomi_sdm845 -b lin20gb ~/android_kernel_xiaomi_sdm845 && cd /home/runner/android_kernel_xiaomi_sdm845 && ls && git submodule init && git submodule update && ls
    - name: Set build date
      id: get-date
      run: | 
        echo ::set-output name=date::$(/bin/date -u "+%Y%m%d")
    - name: execute
      run: cd /home/runner/android_kernel_xiaomi_sdm845 && chmod +x b.sh && ./b.sh
    - name: Kernel Image
      run: cp /home/runner/android_kernel_xiaomi_sdm845/out/arch/arm64/boot/Image.gz-dtb /home/runner/anykernel3/Image.gz-dtb
    - name: zip it
      run:  cd /home/runner/anykernel3 && zip -r9 linpro-${{ steps.get-date.outputs.date }}.zip  * -x README linpro-${{ steps.get-date.outputs.date }}.zip
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel
        path: /home/runner/anykernel3/linpro-${{ steps.get-date.outputs.date }}.zip
